package br.jus.tse.eleitoral.eleitor.integracao.webservices.dto;

public class ASEDTO {

	/*COD_OBJETO	TSE
	COD_SIT_MOVIMENTO	TSE
	NUM_SEQ_REGISTRO_LOTE	TRE 
	COD_OPERADOR	TRE 
	DAT_DIGITACAO	TRE 
	COD_OBJETO_LOTE	TSE/TRE 
	COD_FASE	TRE 
	DAT_OCORRENCIA	TRE 
	DES_COMPLEMENTO	TRE 
	NUM_INSCRICAO	TRE 
	NOM_ELEITOR	TSE
	COD_OBJETO_CARGO_ELETIVO	TRE 
	COD_OBJETO_FUNCAO_ELEITORAL	TRE 
	COD_OBJETO_PARTIDO	TRE 
	COD_OBJETO_FASE	TSE
	COD_OBJETO_MOTIVO_FASE	TRE 
	COD_OBJETO_DAT_ELEICAO	TRE 
	COD_OBJETO_LOTSEQRAEFASE	TSE
	COD_OBJETO_LOCALIDADE	TRE */

	private String codObjeto;
	private String codigoSituacaoMovimento;
	
	
}
